### PR TITLE
Fix link label parsing for imenu

### PR DESCRIPTION
**Pull request by clemera**

### CODE REVIEW

**Comment by wasamasa** [comment]
Hm, this is good, but I think we can do even better. What we really want is the string content of the node which is defined by taking all string descendants and joining them with space:

```elisp
(mapconcat 'identity (esxml-find-descendants 'stringp node) " ")
```

This way a node like `(a nil (span nil "foo") "bar" (span nil "baz"))` is handled correctly and is presented as "foo bar baz" instead of "bar".

**Comment by clemera** [comment]
Good idea, are there cases where the strings aren't already separated? In my case the above adds extra spaces to the titles so this would work better:

    (apply #'concat (esxml-find-descendants #'stringp node))

**Comment by wasamasa** [comment]
No, that's not how HTML works. See the following:

- https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute
- https://dom.spec.whatwg.org/#concept-descendant-text-content
- https://infra.spec.whatwg.org/#string-concatenate

Basically, you ensure exactly one space of whitespace between each node. Everything else is presentational and therefore out of scope for shr.el.

**Comment by clemera** [comment]
Okay, maybe we can just use your suggestion but remove double spaces in the label? I imagine this will happen quite often.

**Comment by wasamasa** [comment]
Another part in the spec suggests removing surrounding spaces first, so I'd use that instead of the identity function.

**Comment by clemera** [comment]
Okay, any surrounding white space is now removed from the text nodes first.

**Comment by wasamasa** [comment]
Sorry to be a buzzkill, but we may not use `subr-x.el` stuff as it's documented to be experimental and functions in there may or may not become parts of Emacs proper. `esxml.el` happens to contain a `string-trim-whitespace` helper just for that.

**Comment by clemera** [comment]
Okay no problem, I have added the require inside the function, because it's not required by nov. I can also add it a top level if you prefer that.

**Comment by wasamasa** [comment]
Works for me. Thanks again for catching this!

**Comment by clemera** [comment]
Thanks!

**Pull request merged**
