### PR TITLE
Add forward and backward document navigation

### PR DESCRIPTION
**Pull request by xiongtx**
Clearly inspired by Info's `Info-history-back` and `Info-history-forward`.

### CODE REVIEW

**Comment by wasamasa** [comment]
I'm sorry, but I'll have to decline this because accepting this will introduce a different internal storage model (and make `nov-documents-index` mostly useless).  I'd like to ponder more about how to change it so that *all* envisioned future features will work well with it.

**Comment by xiongtx** [comment]
> accepting this will introduce a different internal storage model (and make `nov-documents-index` mostly useless)

How so? AFAICT `nov-documents-index` stores the location of the current chapter. That's not impacted at all.

**Comment by wasamasa** [comment]
I'm speaking of the documents stack and the `cadar` on it.

**Comment by xiongtx** [comment]
Fair enough. I suppose you can re-introduce this functionality when you've decided on the internal representation.

**Pull request closed without merging**
